[workspace]
members = ["generator", "processor"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Ryan Armstrong"]
description = "Coursework for Casey Muratori's 'Performance Aware Programming' course."

# If I get through most of part 3 and should be seeing major performance
# improvements but I'm not then it could be that the rust compiler's
# optimizations are outdoing my own. In that case, just set opt-level to 0 and
# use the shitty non-compiler-optimized version.
#
# opt-level 1 seems to vectorize loops which I don't think we want at this point
# so just use opt-level 0 for now.
[profile.dev.package.processor]
opt-level = 0
debug = true

[profile.dev.package.generator]
opt-level = 2
debug = true
