[package]
name = "reptest_simple_buffer_writes"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
repetition_tester = { path = "../../libs/repetition_tester" }
