[package]
name = "repetition_testing"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
performance_metrics = { path = "../libs/performance_metrics" }
winapi = { version = "0.3.9", features = ["errhandlingapi", "fileapi", "handleapi"] }
