[package]
name = "processor"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[features]
profiling = []

[dependencies]
winapi = { version = "0.3.9", features = ["profileapi"] }
performance_metrics = { path = "../libs/performance_metrics" }
