[package]
name = "reptest_nontemporal_stores"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
winapi = { version = "0.3.9", features = ["memoryapi"] }
repetition_tester = { path = "../../libs/repetition_tester" }
